spring:


  datasource:
    url: jdbc:mysql://localhost:5431/library_management
    username: root
    password: 303ehd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
